#!/bin/bash
# Copyright (C) 2026 Lenik <repoman@bodz.net>
# SPDX-License-Identifier: AGPL-3.0-or-later

mirror_probe_url() {
    local base="${1%/}"
    printf '%s/core/os/x86_64/core.db\n' "$base"
}

render_mirror_config() {
    local url="${1%/}"
    local outpath="$2"

    cat >"$outpath" <<EOF
# Generated by lrm
Server = ${url}/\$repo/os/\$arch
EOF
}

apply_mirror() {
    local url="${1%/}"
    local path="/etc/pacman.d/mirrorlist"
    local backup="${path}.lrm.bak"
    local tmp

    vlog2 "applying pacman mirror $url to $path"

    if [[ ! -f "$backup" && -f "$path" ]]; then
        elevated "$backup" cp -a "$path" "$backup"
    fi

    tmp="$(mktemp "${TMPDIR:-/tmp}/lrm-mirrorlist.XXXXXX")"
    render_mirror_config "$url" "$tmp"
    install_as_root "$tmp" "$path"
    rm -f "$tmp"

    if [[ "${LRM_CONFIG_ONLY:-0}" -eq 1 ]]; then
        vlog2 "skipping pacman -Syy (--config-only)"
    elif command -v pacman >/dev/null 2>&1; then
        run_as_root pacman -Syy >/dev/null 2>&1 || warn "$(_ 'warning: pacman -Syy failed')"
    fi
    log "$(printf "$(_ 'wrote %s')" "$path")"
}

parse_apply_opts() {
    LRM_CONFIG_ONLY=0
    PARSE_APPLY_TARGET=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
        -c|--config-only) LRM_CONFIG_ONLY=1; shift ;;
        -e|--everything|-E|--epel|-r|--releasever|--arch|--appstream|--crb|--powertools|--no-epel|--no-appstream|--no-crb|--no-baseos)
            die "$(printf "$(_ 'option %s is only supported on RPM-based systems')" "$1")"
            ;;
        -a|--all|-s|--src|-u|--updates|-b|--backports|--security|--minimal|--no-src|--no-updates|--no-backports|--no-security|--contrib|--non-free|--firmware|--suite)
            die "$(printf "$(_ 'option %s is only supported on Debian-based systems')" "$1")"
            ;;
        -h|--help) usage; exit 0 ;;
        -*) die "$(printf "$(_ 'unknown option: %s')" "$1")" ;;
        *)
            [[ -z "$PARSE_APPLY_TARGET" ]] || die "$(printf "$(_ 'unexpected argument: %s')" "$1")"
            PARSE_APPLY_TARGET="$1"
            shift
            ;;
        esac
    done

    [[ -n "$PARSE_APPLY_TARGET" ]] || die "$(_ 'usage: lrm use [-c|--config-only] ALIAS|NUM')"
    export LRM_CONFIG_ONLY
}

parse_sel_opts() {
    LRM_CONFIG_ONLY=0
    PING_COUNT=3
    PING_TIMEOUT=2

    while [[ $# -gt 0 ]]; do
        case "$1" in
        -c|--config-only) LRM_CONFIG_ONLY=1; shift ;;
        -e|--everything|-E|--epel|-r|--releasever|--arch|--appstream|--crb|--powertools|--no-epel|--no-appstream|--no-crb|--no-baseos)
            die "$(printf "$(_ 'option %s is only supported on RPM-based systems')" "$1")"
            ;;
        -a|--all|-s|--src|-u|--updates|-b|--backports|--security|--minimal|--no-src|--no-updates|--no-backports|--no-security|--contrib|--non-free|--firmware|--suite)
            die "$(printf "$(_ 'option %s is only supported on Debian-based systems')" "$1")"
            ;;
        -n|--count)
            [[ $# -ge 2 ]] || die "$(_ 'usage: -n|--count N')"
            PING_COUNT="$2"
            shift 2
            ;;
        -W|--timeout)
            [[ $# -ge 2 ]] || die "$(_ 'usage: -W|--timeout SEC')"
            PING_TIMEOUT="$2"
            shift 2
            ;;
        --ref)
            [[ $# -ge 2 ]] || die "$(_ 'usage: --ref BYTES')"
            BWTEST_REF_BYTES="$2"
            shift 2
            ;;
        -h|--help) usage; exit 0 ;;
        -*) die "$(printf "$(_ 'unknown option: %s')" "$1")" ;;
        *) die "$(printf "$(_ 'unexpected argument: %s')" "$1")" ;;
        esac
    done

    export LRM_CONFIG_ONLY PING_COUNT PING_TIMEOUT BWTEST_REF_BYTES
}
